<?php

namespace Umanit\BlockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PanelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelRepository extends EntityRepository
{
}
