<?php

namespace Umanit\BlockBundle\Repository\Block;

/**
 * TitleAndTextBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitleAndTextBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
